### ISSUE TITLE
IndexError on SHA1 Hash Calculation

### ISSUE THREAD

**Issue by kero3009destiny** [AidenPearce369/elfxtract#1]
```
root@GH0STLUT:/mnt/d/Downloads/VITA/PkgDecrypt/release_win64_7/LIVETWEET_decrypted/module/elfxtract# python3 main.py --file twitter_plugin.suprx.elf -i

         _____ _     ________   ___                  _
        |  ___| |    |  ___\ \ / / |                | |
        | |__ | |    | |_   \ V /| |_ _ __ __ _  ___| |_
        |  __|| |    |  _|  /   \| __| '__/ _` |/ __| __|
        | |___| |____| |   / /^\ \ |_| | | (_| | (__| |_
        \____/\_____/\_|   \/   \/\__|_|  \__,_|\___|\__|

                        @aidenpearce369

***************************************************************************

> FILE INFO :

    ELF Name       :  twitter_plugin.suprx.elf
    ELF Type       :  ELF 32-bit LSB ARM
    ELF Arch       :  EABI5 version 1 (SYSV)

Traceback (most recent call last):
  File "/mnt/d/Downloads/VITA/PkgDecrypt/release_win64_7/LIVETWEET_decrypted/module/elfxtract/main.py", line 118, in <module>
    basicinfo(args.file)
  File "/mnt/d/Downloads/VITA/PkgDecrypt/release_win64_7/LIVETWEET_decrypted/module/elfxtract/main.py", line 53, in basicinfo
    file_details(filename)
  File "/mnt/d/Downloads/VITA/PkgDecrypt/release_win64_7/LIVETWEET_decrypted/module/elfxtract/checkfile.py", line 20, in file_details
    print("\tELF SHA1 Hash".ljust(15)+" : "+file_data[5])
IndexError: list index out of range```

**Comment by dabiri1994** [comment]
> ```
> root@GH0STLUT:/mnt/d/Downloads/VITA/PkgDecrypt/release_win64_7/LIVETWEET_decrypted/module/elfxtract# python3 main.py --file twitter_plugin.suprx.elf -i
> 
>          _____ _     ________   ___                  _
>         |  ___| |    |  ___\ \ / / |                | |
>         | |__ | |    | |_   \ V /| |_ _ __ __ _  ___| |_
>         |  __|| |    |  _|  /   \| __| '__/ _` |/ __| __|
>         | |___| |____| |   / /^\ \ |_| | | (_| | (__| |_
>         \____/\_____/\_|   \/   \/\__|_|  \__,_|\___|\__|
> 
>                         @aidenpearce369
> 
> ***************************************************************************
> 
> > FILE INFO :
> 
>     ELF Name       :  twitter_plugin.suprx.elf
>     ELF Type       :  ELF 32-bit LSB ARM
>     ELF Arch       :  EABI5 version 1 (SYSV)
> 
> Traceback (most recent call last):
>   File "/mnt/d/Downloads/VITA/PkgDecrypt/release_win64_7/LIVETWEET_decrypted/module/elfxtract/main.py", line 118, in <module>
>     basicinfo(args.file)
>   File "/mnt/d/Downloads/VITA/PkgDecrypt/release_win64_7/LIVETWEET_decrypted/module/elfxtract/main.py", line 53, in basicinfo
>     file_details(filename)
>   File "/mnt/d/Downloads/VITA/PkgDecrypt/release_win64_7/LIVETWEET_decrypted/module/elfxtract/checkfile.py", line 20, in file_details
>     print("\tELF SHA1 Hash".ljust(15)+" : "+file_data[5])
> IndexError: list index out of range```
> ```

Hello, have you found a solution for this issue?

**Comment by kero3009destiny** [comment]
Sadly no, please update the issue if you do 🙏
